PREFIX dl: <http://data.europa.eu/eli/eli-draft-legislation-ontology#>
SELECT ?status WHERE { GRAPH <https://data.oireachtas.ie/graph/bill/2025/60> { <https://data.oireachtas.ie/ie/oireachtas/bill/2025/60#process> dl:process_status ?status } }
