PREFIX oir: <https://data.oireachtas.ie/ontology#>
SELECT ?stage ?order WHERE { GRAPH <https://data.oireachtas.ie/graph/bill/2025/60> { ?stage a oir:BillStage ; oir:progressStage ?order } } ORDER BY ?order
