SELECT ?member ?term WHERE {
  GRAPH ?graph {
    ?member a <https://data.oireachtas.ie/ontology#Member> ;
      <https://data.oireachtas.ie/ontology/members#hasMembersMembership> ?membership .
    ?membership a <https://data.oireachtas.ie/ontology/members#OireachtasMembership> ;
      <https://data.oireachtas.ie/ontology/members#inHouseTerm> ?term ;
      <https://data.oireachtas.ie/ontology/members#hasMembershipDateRange> ?range .
    FILTER NOT EXISTS { ?range <https://data.oireachtas.ie/ontology/members#EndDate> ?end }
  }
  FILTER(STRSTARTS(STR(?graph), "https://data.oireachtas.ie/graph/member/"))
}
ORDER BY ?member ?term
