PREFIX : <https://data.oireachtas.ie/ontology/members#>
SELECT ?party ?code ?term WHERE {
  GRAPH <https://data.oireachtas.ie/graph/parties> {
    VALUES ?party { <https://data.oireachtas.ie/ie/oireachtas/party/dail/31/Fine_Gael> <https://data.oireachtas.ie/ie/oireachtas/party/dail/31/Independent> }
    ?party a :ParliamentaryMemberCollection ; :partyCode ?code ; :activeDuringTerm ?term .
    FILTER(
      (?party = <https://data.oireachtas.ie/ie/oireachtas/party/dail/31/Fine_Gael> && EXISTS { ?party a :ParliamentaryParty }) ||
      (?party = <https://data.oireachtas.ie/ie/oireachtas/party/dail/31/Independent> && EXISTS { ?party a :IndependentMemberCollection })
    )
  }
} ORDER BY ?party
